<?php
/**
 * H3 Tour Management - Batch Convert Tours
 * Simple script to convert all HTML tours to PHP
 */

// Configuration
define('TOUR_DIR', '/h3panos');
define('GA_MEASUREMENT_ID', 'G-08Q1M637NJ');
define('CREATE_BACKUPS', true);

// Get the document root
$root = dirname(__FILE__) . '/../../../..';
$tour_base_dir = $root . TOUR_DIR;

echo "H3 Tour Batch Conversion Script\n";
echo "===============================\n\n";

if (!is_dir($tour_base_dir)) {
    die("Error: Tour directory not found at: $tour_base_dir\n");
}

echo "Tour directory: $tour_base_dir\n\n";

// Function to create PHP index file
function create_php_index($tour_path, $tour_name) {
    $html_file = $tour_path . '/index.html';
    $htm_file = $tour_path . '/index.htm';
    $php_file = $tour_path . '/index.php';
    
    // Determine which HTML file exists
    $source_file = '';
    if (file_exists($html_file)) {
        $source_file = $html_file;
    } elseif (file_exists($htm_file)) {
        $source_file = $htm_file;
    } else {
        return false;
    }
    
    // Read the original HTML content
    $html_content = file_get_contents($source_file);
    if ($html_content === false) {
        return false;
    }
    
    // Extract the title
    $title = $tour_name;
    if (preg_match('/<title>(.*?)<\/title>/i', $html_content, $matches)) {
        $title = trim($matches[1]);
    }
    
    // Create PHP index file with analytics code
    $php_content = '<?php
/**
 * H3 Tour Index File
 * Tour: ' . htmlspecialchars($tour_name) . '
 * Generated by H3 Tour Management Plugin
 */

// Get tour name from directory
$tour_name = basename(__DIR__);

// Analytics configuration
$ga_measurement_id = "' . GA_MEASUREMENT_ID . '";
$analytics_enabled = true;
$track_interactions = true;
$track_time_spent = true;

// Custom analytics parameters (modify as needed)
$custom_dimensions = array();
$custom_events = array();

// Start output
?>
<!DOCTYPE html>
' . substr($html_content, strpos($html_content, '<html'));
    
    // Insert Google Analytics code before </head>
    $analytics_code = '
<!-- Google Analytics -->
<?php if ($analytics_enabled && !empty($ga_measurement_id)) : ?>
<script async src="https://www.googletagmanager.com/gtag/js?id=<?php echo $ga_measurement_id; ?>"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag(\'js\', new Date());
  
  gtag(\'config\', \'<?php echo $ga_measurement_id; ?>\', {
    \'page_title\': \'' . addslashes($title) . '\',
    \'page_path\': \'' . TOUR_DIR . '/<?php echo $tour_name; ?>/\'
  });
  
  // Track tour view event
  gtag(\'event\', \'tour_view\', {
    \'tour_name\': \'<?php echo $tour_name; ?>\',
    \'tour_title\': \'' . addslashes($title) . '\'
  });
</script>

<!-- Custom Analytics Tracking -->
<script>
  // Track tour engagement
  document.addEventListener(\'DOMContentLoaded\', function() {
    <?php if ($track_interactions) : ?>
    // Track panorama interactions
    if (typeof tour !== \'undefined\' && tour.on) {
      tour.on(\'view-change\', function(e) {
        if (typeof gtag !== \'undefined\') {
          gtag(\'event\', \'panorama_interaction\', {
            \'event_category\': \'Tour Engagement\',
            \'event_label\': e.view || \'unknown\',
            \'tour_name\': \'<?php echo $tour_name; ?>\'
          });
        }
      });
    }
    <?php endif; ?>
    
    <?php if ($track_time_spent) : ?>
    // Track time on page
    let startTime = Date.now();
    window.addEventListener(\'beforeunload\', function() {
      let timeSpent = Math.round((Date.now() - startTime) / 1000);
      if (typeof gtag !== \'undefined\') {
        gtag(\'event\', \'timing_complete\', {
          \'name\': \'tour_session\',
          \'value\': timeSpent,
          \'event_category\': \'Tour Engagement\',
          \'event_label\': \'<?php echo $tour_name; ?>\'
        });
      }
    });
    <?php endif; ?>
  });
</script>
<?php endif; ?>
<!-- End Google Analytics -->

</head>';
    
    // Replace </head> with analytics code + </head>
    $php_content = str_replace('</head>', $analytics_code, $php_content);
    
    // Add custom PHP tracking at the end of body
    $tracking_code = '
<!-- Additional PHP Tracking -->
<?php
// You can add custom PHP tracking code here
// For example, log visits to a database, send notifications, etc.
?>
</body>';
    
    // Replace </body> with tracking code
    $php_content = str_replace('</body>', $tracking_code, $php_content);
    
    // Write the PHP file
    if (file_put_contents($php_file, $php_content) === false) {
        return false;
    }
    
    // Create backup of original file
    if (CREATE_BACKUPS) {
        copy($source_file, $source_file . '.backup');
    }
    
    // Delete the original HTML file
    unlink($source_file);
    
    // Create .htaccess to ensure index.php is used
    $htaccess_content = '# H3 Tour Management - Use PHP index
DirectoryIndex index.php index.html index.htm

# Optional: Prevent direct access to backup files
<FilesMatch "\.backup$">
    Order Allow,Deny
    Deny from all
</FilesMatch>';
    
    file_put_contents($tour_path . '/.htaccess', $htaccess_content);
    
    return true;
}

// Process tours
$total = 0;
$converted = 0;
$skipped = 0;
$failed = 0;

$dir = new DirectoryIterator($tour_base_dir);
foreach ($dir as $fileinfo) {
    if ($fileinfo->isDir() && !$fileinfo->isDot()) {
        $tour_name = $fileinfo->getFilename();
        $tour_path = $fileinfo->getPathname();
        $total++;
        
        echo "Processing: $tour_name\n";
        
        // Check if already has PHP file
        if (file_exists($tour_path . '/index.php')) {
            echo "  → Already has index.php (skipped)\n";
            $skipped++;
            continue;
        }
        
        // Check for HTML files
        if (!file_exists($tour_path . '/index.html') && !file_exists($tour_path . '/index.htm')) {
            echo "  → No index.html or index.htm found (failed)\n";
            $failed++;
            continue;
        }
        
        // Convert to PHP
        if (create_php_index($tour_path, $tour_name)) {
            echo "  → Successfully converted to PHP\n";
            $converted++;
        } else {
            echo "  → Failed to convert\n";
            $failed++;
        }
    }
}

echo "\n";
echo "Conversion Complete!\n";
echo "===================\n";
echo "Total tours: $total\n";
echo "Converted: $converted\n";
echo "Skipped (already PHP): $skipped\n";
echo "Failed: $failed\n";

if (CREATE_BACKUPS) {
    echo "\nOriginal HTML files have been backed up with .backup extension\n";
}
?>